### ISSUE TITLE
有了Openid后可以开放API出来了是把？

### ISSUE THREAD

**Issue by rebron1900** [justmemos/memos#16]
看到一些flomo的工具如：
https://github.com/it5200/flomoPlus
https://github.com/woodgear/retalk

**Comment by boojack** [comment]
openId 是个字段名，目前主要用于 Open API 的调用，使用示例：
![image](https://user-images.githubusercontent.com/24653555/148736078-bfe09e27-6caa-4f4f-b4c9-39821e3501a2.png)
