### ISSUE TITLE
Bug: 时区不同导致前端报错

### ISSUE THREAD

**Issue by Viyerelu23333** [justmemos/memos#21]
可能与 #2 相关。
在部署时发现，时区错误（笔记时间在未来时）会导致网页无法加载／提交笔记，刷新后提示「😭 请求数据失败了」。此时数据库内有笔记、API 正常响应，但日期在未来。影响范围不只是时区设置错误，跨时区访问也可能会造成此问题。

　是否可以在后端使用 UNIX 时间戳来存放日期，前端解析到本机时区呢？

若部署在「Asia/Shanghai」，尝试将系统调整为「UTC」，发布笔记后应该可以复现。

---
一些不相关的问题：
- 数据库若是要更新，请问如何迁移原有数据啊；
- 在自建部署时，网页仍会加载 Google Analytics。

**Comment by boojack** [comment]
>是否可以在后端使用 UNIX 时间戳来存放日期，前端解析到本机时区呢？

正好目前正在做后台数据库关于 createdAt/updatedAt 和 ID 的重构，准备用时间戳来存 createdTs/updatedTs。

>数据库若是要更新，请问如何迁移原有数据？

因为正处于开发中，我尽量保证较少的涉及到数据库 schema 变更，但如果有需要更改的话（如上），想到了几种方法：
1. 新增数据的导出导入功能；
2. 另起一个平台来可视化管理 .db 文件；（更倾向于这种）

>在自建部署时，网页仍会加载 Google Analytics

这个可以去掉。

**Comment by rebron1900** [comment]
第一个方式更好，以后的导入导出肯定要做的。
