### ISSUE TITLE
[讨论] flomo、memos的这种列表式的标签管理方式到底好不好？

### ISSUE THREAD

**Issue by rebron1900** [justmemos/memos#22]
如题，目前我有不到八个标签，标签列表已经很长了，如果以后有几十上百个如何管理？
所以想和大家讨论一下这种列表形式到底好不好？

如果换成标签云的形式会不会好一些？或者有没有其他更具美感和更方便的标签管理形式呢。

![image](https://user-images.githubusercontent.com/7929884/149853895-6c6eb870-dad0-4f30-9dff-690e222b0fb3.png)

**Comment by boojack** [comment]
力推使用“常用标签”上面的“快速检索”，之后会用“标签云”或者其他形式代替掉列表。
（建议把「讨论」相关的放在 Discussions 上，不用 Issues）
