### ISSUE TITLE
The most recent commit has serious errors.

### ISSUE THREAD

**Issue by NoverNobida** [justmemos/memos#27]
The most recent commit has serious errors.
Login:
```
😟 code=500, 
message=Failed to set login session, 
internal=failed to get session, err:
securecookie: the value is not valid
```
Sign up, use username `test`:
```
😟 code=401,
 message=Existed user found: test
```

**Comment by boojack** [comment]
fixed in: https://github.com/justmemos/memos/commit/ef8034836c7f79ec014973475909fe8c8526e1eb

**Comment by NoverNobida** [comment]
👍
I have observed that the URL of openapi in the setting has changed. Is it possible to **get notes** through the api now?

**Comment by boojack** [comment]
> I have observed that the URL of openapi in the setting has changed. Is it possible to **get notes** through the api now?

Of course, it will be updated in the next PR.

**Comment by boojack** [comment]
@NoverNobida Check this [commit](https://github.com/justmemos/memos/commit/c77996a8914d29bb1b21d537da2845cde8f09e2a#diff-e3302fa7fe65284d10a8f46bad75c6e182a9b39a0400fb09f888d0dde5a79bf9) for getting all memos with open api.

**Comment by NoverNobida** [comment]
Now the API works fine. But has the database structure or directory changed? The previous data is no longer available.

**Comment by boojack** [comment]
The database schema and its directory have been changed, take a look in its simple changelog in https://github.com/justmemos/memos/pull/26
And the next version is still WIP, I just suggest to give it a try but not in production with [deploy guide with docker](https://github.com/justmemos/memos/blob/main/docs/deploy/docker-deploy-guide.md).

**Comment by NoverNobida** [comment]
I tried the latest docker image and found that even though I used `-mode release` or `-data /var/opt/memos`, the data was still kept at `/usr/local/memos/memos_dev.db`, not `/var/opt/memos/memos_release.db`.

**Comment by boojack** [comment]
The next image use inputs from env variables not flag.

How to set environment variables in docker: https://stackoverflow.com/questions/30494050/how-do-i-pass-environment-variables-to-docker-containers
Related code: https://github.com/justmemos/memos/blob/main/bin/server/cmd/profile.go#L43
