### ISSUE TITLE
手机页面输入框无法输入

### ISSUE THREAD

**Issue by yylqing** [justmemos/memos#30]
使用`memo:next`和`memo:latest` docker镜像部署，使用手机浏览器打开时，出现输入框无法聚焦的问题，倒是无法输入。
使用了微信内置浏览器，Chrome，Safari测试，情况一样。
![c712e46bf2852bc1f5fc6a817e94950](https://user-images.githubusercontent.com/18625743/153534201-cb597b86-e0f9-4976-a733-914345b3040a.jpg)

**Comment by boojack** [comment]
应该已经修复了，再试试看

**Comment by happy2h** [comment]
更新后手机客户端样式和以前不一样了

**Comment by boojack** [comment]
> 更新后手机客户端样式和以前不一样了

最近在尝试调整页面布局，手机端样式已被移除。
