### ISSUE TITLE
No way to exit recycle bin

### ISSUE THREAD

**Issue by ibebop** [justmemos/memos#35]
Hi team great work! I found 2 bugs and hope can help improve

Realized 2 issues for this: 

1. entering into recycle bin and there is no exit button; got stuck there forever even close the pane and reopen
2. created a note and deleted it, but it was not shown in the recycle bin, seems recycle bin is not functioning

**Comment by boojack** [comment]
Thanks for your interest. I just try 2 issues in [demo](https://memos.onrender.com/).

1. You can go back by click the `username`. And its UX really needs to be rethink and improve.
<img width="855" alt="image" src="https://user-images.githubusercontent.com/24653555/156091199-1f9778db-8b60-434d-b74d-e99edca1b9a1.png">
2. I just found it works right when deleting.

**Comment by ibebop** [comment]
发现在obsidian里创建时不是建在query.md里，而是创建了一个yyyy-mm-dd的note，另外这两天看发现名字MEMO[😊]不显示了发自我的iPhone------------------ Original ------------------From: STEVEN  ***@***.***>Date: Fri,Mar 11,2022 4:37 AMTo: justmemos/memos ***@***.***>Cc: FYH ***@***.***>, Author ***@***.***>Subject: Re: [justmemos/memos] No way to exit recycle bin (Issue #35)
Closed #35.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/justmemos/memos/issues/35#event-6220580504",
"url": "https://github.com/justmemos/memos/issues/35#event-6220580504",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by boojack** [comment]
> 发现在obsidian里创建时不是建在query.md里，而是创建了一个yyyy-mm-dd的note，另外这两天看发现名字MEMO[😊]不显示了发自我的iPhone------------------ Original ------------------From: STEVEN ***@***.***>Date: Fri,Mar 11,2022 4:37 AMTo: justmemos/memos ***@***.***>Cc: FYH ***@***.***>, Author ***@***.***>Subject: Re: [justmemos/memos] No way to exit recycle bin (Issue #35) Closed #35. —Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***> [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "[#35 (comment)](https://github.com/justmemos/memos/issues/35#event-6220580504)", "url": "[#35 (comment)](https://github.com/justmemos/memos/issues/35#event-6220580504)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

Maybe you are using the other "memos" from this repo.

**Comment by ibebop** [comment]
I got the plugin from obsidian community plugins发自我的iPhone------------------ Original ------------------From: STEVEN  ***@***.***>Date: Sat,Mar 12,2022 10:52 AMTo: justmemos/memos ***@***.***>Cc: FYH ***@***.***>, Author ***@***.***>Subject: Re: [justmemos/memos] No way to exit recycle bin (Issue #35)

发现在obsidian里创建时不是建在query.md里，而是创建了一个yyyy-mm-dd的note，另外这两天看发现名字MEMO[😊]不显示了发自我的iPhone------------------ Original ------------------From: STEVEN @.>Date: Fri,Mar 11,2022 4:37 AMTo: justmemos/memos @.>Cc: FYH @.>, Author @.>Subject: Re: [justmemos/memos] No way to exit recycle bin (Issue #35) Closed #35. —Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: @.> [ { @.": "http://schema.org", @.": "EmailMessage", "potentialAction": { @.": "ViewAction", "target": "#35 (comment)", "url": "#35 (comment)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { @.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

Maybe you are using the other "memos" from this repo.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/justmemos/memos/issues/35#issuecomment-1065796966",
"url": "https://github.com/justmemos/memos/issues/35#issuecomment-1065796966",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
