### ISSUE TITLE
请问如何不丢失数据更新镜像

### ISSUE THREAD

**Issue by happy2h** [justmemos/memos#36]
在latest和next切换时，之前的用户和memos都丢失了，想请教下如何保留数据更新容器里的镜像

**Comment by happy2h** [comment]
还有那个数据只有导出，没有找到导入的入口。

**Comment by happy2h** [comment]
> 1. 先从 latest 里导出数据（我记得好像是做了的
> 2. next 的导入还没做
latest有导出，但是没有导入

**Comment by boojack** [comment]
latest 不会再更新了，所以不会做导入功能。等 next 做的差不多后（maybe 1个月内），可以转为用 next
