### ISSUE TITLE
memos升级后无法使用

### ISSUE THREAD

**Issue by iorihu2001** [justmemos/memos#45]
原有的memo笔记都无法读取了，写新的memo会在daily notes 中记录，但是也无法提取。
打开memos就会报fetch error的错误。
请问有遇到过这个情况的吗？

**Comment by boojack** [comment]
dev 版本 database schema 有较大变更，目前数据迁移逻辑还没来得及完善，建议还是使用 `neosmemo/memos:latest`

**Comment by iorihu2001** [comment]
> dev 版本 database schema 有较大变更，目前数据迁移逻辑还没来得及完善，建议还是使用 `neosmemo/memos:latest`

好的，谢谢，我试试

**Comment by iorihu2001** [comment]
我看memos又有更新了，更新了一下，现在是原有的memos可以读取了，但是无法写入新的memos，报错如下：
![image](https://user-images.githubusercontent.com/12798713/164174543-c1315434-ab34-4d65-a9e1-6915915c4cb8.png)

**Comment by boojack** [comment]
> 我看memos又有更新了，更新了一下，现在是原有的memos可以读取了，但是无法写入新的memos，报错如下： ![image](https://user-images.githubusercontent.com/12798713/164174543-c1315434-ab34-4d65-a9e1-6915915c4cb8.png)

你可能找错 repo 了 :)
